# read .md first!
# this is an example for jinja configuration language in helm chart


# "{{-" means get rid of leftover whitespaces
# "and" returned the boolean sum of two variables
# "not"  
{{- if and .Values.global.image_pull_secret.enabled (not .Values.global.image_pull_secret.use_existing) }}

{{- $registryAuthDocument := dict -}}
{{- $_ := set $registryAuthDocument "username" .Values.global.image_pull_secret.username }}
{{- $_ := set $registryAuthDocument "password" .Values.global.image_pull_secret.password }}
{{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $registryUrl := trimSuffix "/" .Values.global.private_registry }}
{{- $dockerAuthDocument := dict $registryUrl $registryAuthDocument }}
{{- $dockerConfigJSONDocument := dict "auths" $dockerAuthDocument -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.image_pull_secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: vod
    core: "true"
data:
  .dockerconfigjson: {{ $dockerConfigJSONDocument | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}